#主要部分
Main:
  #进入新玩家后推送给服务器内所有玩家的点击欢迎按钮
  button: "&f[&a点击欢迎&f]"
  #鼠标停留在按钮上显示的文本，新玩家名：[new]
  button_message: "&a点击欢迎玩新家 &e[new]"
  #点击按钮后玩家聊天框自动获取的的欢迎文本，新玩家名：[new]
  welcome: "欢迎新玩家 [new] 加入服务器！"
#文本设置
Messages:
  #插件前缀名
  prefix: "&f[&3欢迎系统&f] "
  #重载插件
  reload: "&aWelcome插件已重载！"
  #没有权限
  error: "&c你没有使用该命令的权限或者命令不存在！"